# Generated by Django 6.0.3 on 2026-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(max_length=200)),
                ('link_projeto', models.URLField()),
                ('imagem', models.URLField()),
            ],
        ),
    ]
