# Generated by Django 6.0.3 on 2026-03-10 14:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_projeto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
