# Generated by Django 6.0.3 on 2026-03-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_criado_em_alter_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
