# Generated by Django 6.0.3 on 2026-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_imagem_alter_projeto_link_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='link_projeto',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
